server:
  port: 0  # 게이트웨이 서비스가 실행될 포트 번호

spring:
  application:
    name: gateway-service  # 애플리케이션 이름을 'gateway-service'로 설정
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨

  profiles: # 현재 활성화할 프로파일을 지정
    active: local # config server 에서 local 파일을 기준으로 설정파일을 검색하도록 지정한다.
  config:
    import: "configserver:" # config server 로 부터 설정 파일을 가져오도록 설정


  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

    gateway:
      routes:  # Spring Cloud Gateway의 라우팅 설정
        - id: order-service  # 라우트 식별자
          uri: lb://order-service  # 'order-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/orders/**  # api/order/** 경로로 들어오는 요청을 이 라우트로 처리

        - id: product-service  # 라우트 식별자
          uri: lb://product-service  # 'product-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/products/**  # api/product/** 경로로 들어오는 요청을 이 라우트로 처리

        - id: auth-service  # 라우트 식별자
          uri: lb://auth-service  # 'product-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/auth/**  # /api/auth/signIn  경로로 들어오는 요청을 이 라우트로 처리
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정

management:
  endpoints: # 특정 엔드포인트 노출
    web:
      exposure:
        include: refresh  #refresh 엔드포인트를 활성화한다.
        # /actuator/refresh 경로에서 config server의 설정 정보를 다시 가져오도록 강제로 갱신 요청을 보낸다 (동적 변경)

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
